local opt = vim.opt

opt.completeopt = "preview,menuone,noselect"
opt.wrap = false
opt.expandtab = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.shiftround = true
opt.showmode = false
opt.signcolumn = "yes"
opt.smartindent = true
opt.ignorecase = true
opt.smartcase = true
opt.undofile = true
opt.timeoutlen = 300
opt.updatetime = 50
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.termguicolors = true
opt.cursorline = true
